import type { CategoryKey } from './types'

export const APP_CONFIG = {
  search: {
    debounceMs: 150,
    minQueryLength: 2,
    minRequestIntervalMs: 1100,
    cacheTtlMs: 24 * 60 * 60 * 1000,
    limit: 7,
  },
  overpass: {
    radiusM: 2800,
    townRadiusM: 4400,
    cityRadiusM: 6000,
    townPackRadiusM: 7000,
    cityPackRadiusM: 12_000,
    tileSizeM: 2500,
    minTileSizeM: 800,
    editedBoundaryPaddingM: 350,
    maximumEditedRadiusM: 15_000,
    timeoutSeconds: 22,
    overallTimeoutMs: 110_000,
    packDownload: {
      partTimeoutSeconds: 90,
      primaryTimeoutMs: 100_000,
      mirrorTimeoutMs: 55_000,
      maxPrimaryAttempts: 6,
      partRetries: 4,
      backoffMs: [8_000, 15_000, 25_000, 40_000, 60_000],
      pauseBetweenPartsMs: 8_000,
      retryPauseMs: 20_000,
    },
    cacheTtlMs: 6 * 60 * 60 * 1000,
    endpoints: [
      'https://overpass-api.de/api/interpreter',
      'https://overpass.kumi.systems/api/interpreter',
      'https://overpass.private.coffee/api/interpreter',
    ],
  },
  analysis: {
    maxClusterBuildings: 1800,
    maxBufferedBuildings: 280,
    maxRoadBuffers: 220,
    maxClipLinesPrecise: 700,
    maxMapBuildings: 1200,
    maxUnionFeatures: 480,
    unionChunkSize: 32,
    maxElementsPerPart: 20_000,
    maxMergedElements: 40_000,
  },
  boundary: {
    clusterDistanceM: 260,
    clusterBridgeDistanceM: 560,
    cityClusterBridgeDistanceM: 1100,
    minimumClusterSize: 6,
    secondaryClusterMinSize: 4,
    secondaryClusterMinRatio: 0.06,
    buildingBufferM: 115,
    landuseBufferM: 120,
    landuseBridgeDistanceM: 450,
    landuseCenterPreferenceM: 1800,
    centerPreferenceM: 1800,
    townCenterPreferenceM: 2800,
    cityCenterPreferenceM: 4200,
    maximumAreaKm2: 40,
    minimumAreaKm2: 0.025,
    maximumCentroidOffsetM: 2600,
    cityMaximumAreaKm2: 85,
    cityMaximumCentroidOffsetM: 6500,
    simplifyTolerance: 0.00008,
    fallbackRadiusM: 650,
    connectedHullMaxEdgeM: 1400,
    connectedHullGridMaxPoints: 2500,
    dataEdgeFraction: 0.9,
  },
  residential: { buildingBufferM: 24 },
  industrial: { buildingBufferM: 32 },
  roads: {
    defaultWidthM: {
      motorway: 18,
      trunk: 14,
      primary: 11,
      secondary: 9,
      tertiary: 7,
      unclassified: 5.5,
      residential: 5,
      living_street: 4,
      service: 3.5,
    } as Record<string, number>,
  },
  profiles: {
    veryLowBuiltUpMax: 4,
    lowBuiltUpMax: 9,
    mediumBuiltUpMax: 17,
    agriculturalDominantMin: 38,
    mixedIndustrialMin: 16,
  },
  confidence: {
    highScoreMin: 72,
    mediumScoreMin: 43,
  },
} as const

export const CATEGORY_META: Record<CategoryKey, { color: string }> = {
  residential: { color: '#df7048' },
  industrial: { color: '#8d73ad' },
  roads: { color: '#777b7d' },
  green: { color: '#5d9861' },
  water: { color: '#4b9bd0' },
  agricultural: { color: '#e3b43e' },
  other: { color: '#d7d8d4' },
}

export const CATEGORY_ORDER: CategoryKey[] = [
  'residential',
  'industrial',
  'roads',
  'green',
  'water',
  'agricultural',
  'other',
]

export const CATEGORY_PRIORITY: Exclude<CategoryKey, 'other'>[] = [
  'water',
  'roads',
  'industrial',
  'residential',
  'agricultural',
  'green',
]
