import type { L, Locale } from "@/lib/i18n";
import type {
  AnalysisWarningCode,
  BoundaryReasonCode,
  ConfidenceLevel,
  ConfidenceReasonCode,
  SettlementProfileCode,
} from "./types";

export const settlementAnalyzer = {
  name: { bg: "Анализатор на населени места", en: "Settlement Analyzer" } satisfies L,
  tagline: { bg: "Ориентировъчен пространствен анализ", en: "Indicative spatial analysis" } satisfies L,
  metaDescription: {
    bg: "Автоматичен предварителен анализ на български населени места с отворени географски данни.",
    en: "Automatic preliminary analysis of Bulgarian settlements using open geographic data.",
  } satisfies L,
  tools: { bg: "Инструменти", en: "Tools" } satisfies L,
  newAnalysis: { bg: "Нов анализ", en: "New analysis" } satisfies L,
  analyze: { bg: "Анализирай", en: "Analyse" } satisfies L,
  analyzing: { bg: "Анализиране...", en: "Analysing..." } satisfies L,
  searchPlaceholder: { bg: "Търсене на населено място в България", en: "Search for a settlement in Bulgaria" } satisfies L,
  retry: { bg: "Опитай отново", en: "Try again" } satisfies L,
  readyPacks: { bg: "Готови пакети", en: "Ready packs" } satisfies L,
  readyPacksEmpty: { bg: "Няма готови пакети", en: "No ready packs" } satisfies L,
  readyPacksCount: { bg: "Готови пакети ({count})", en: "Ready packs ({count})" } satisfies L,
  downloadPack: { bg: "Свали пакет", en: "Download pack" } satisfies L,
  downloadingPack: { bg: "Сваляне на пакет...", en: "Downloading pack..." } satisfies L,
  cancelDownload: { bg: "Отказ", en: "Cancel" } satisfies L,
  packReady: { bg: "Пакетът е готов", en: "Pack is ready" } satisfies L,
  packDownloadFailed: { bg: "Пакетът не бе свален цял и не е записан. Опитайте отново.", en: "The pack was not downloaded complete and was not saved. Try again." } satisfies L,
  packDownloadCancelled: { bg: "Свалянето бе отказано. Непълен пакет не е записан.", en: "Download was cancelled. An incomplete pack was not saved." } satisfies L,
  packProgress: {
    bg: {
      landuse: "Предназначение на територията",
      buildings: "Сгради",
      roads: "Улична мрежа",
      pois: "Обществени обекти",
      save: "Запис на пакета",
      retry: "Нов опит",
    },
    en: {
      landuse: "Land use",
      buildings: "Buildings",
      roads: "Street network",
      pois: "Public amenities",
      save: "Saving the pack",
      retry: "Retrying",
    },
  } satisfies L<Record<string, string>>,
  mapDisclaimer: {
    bg: "Ориентировъчни отворени данни · Не е официално измерване",
    en: "Indicative open data · Not an official survey",
  } satisfies L,
  boundaryCaption: { bg: "Ориентировъчна застроена зона по отворени данни", en: "Indicative built-up area from open data" } satisfies L,
  sourcesTitle: { bg: "Източници на данните", en: "Data sources" } satisfies L,
  sourceOverpass: { bg: "OpenStreetMap чрез Overpass, изтеглени {date}", en: "OpenStreetMap via Overpass, fetched {date}" } satisfies L,
  sourcePack: { bg: "OpenStreetMap, предварително изтеглени {date}", en: "OpenStreetMap, pre-downloaded {date}" } satisfies L,
  sourceCadastre: { bg: "Кадастър (АГКК): урбанизирани имоти, публична извадка, само за визуална проверка", en: "Cadastre (GCCA): urbanised parcels, public sample, visual check only" } satisfies L,
  sourceRegistry: { bg: "Регистър на населените места (ЕКАТТЕ), АГКК", en: "Settlement register (EKATTE), GCCA" } satisfies L,
  sourceBoundary: { bg: "Граница: {method}", en: "Boundary: {method}" } satisfies L,
  zoomIn: { bg: "Увеличи мащаба", en: "Zoom in" } satisfies L,
  zoomOut: { bg: "Намали мащаба", en: "Zoom out" } satisfies L,
  editTooltip: { bg: "Преместете точките, за да коригирате границата.", en: "Drag the points to adjust the boundary." } satisfies L,
  editSubtext: { bg: "Изберете „Отказ“, за да отмените промените.", en: "Choose Cancel to discard changes." } satisfies L,
  searchFailed: { bg: "Търсенето не бе успешно.", en: "Search did not succeed." } satisfies L,
  searchBusy: { bg: "Услугата за търсене е временно натоварена. Изчакайте малко и опитайте отново.", en: "The search service is busy. Wait a moment and try again." } satisfies L,
  searchUnavailable: { bg: "Търсенето временно не е достъпно. Опитайте отново.", en: "Search is temporarily unavailable. Try again." } satisfies L,
  analysisUnexpected: { bg: "Анализът не бе завършен поради неочаквана грешка.", en: "The analysis did not finish because of an unexpected error." } satisfies L,
  geodataUnavailable: { bg: "Отворените географски данни временно не са достъпни.", en: "Open geographic data are temporarily unavailable." } satisfies L,
  settlementTooLarge: { bg: "Населеното място е твърде голямо за този инструмент. Изберете по-малко населено място.", en: "This settlement is too large for this tool. Choose a smaller settlement." } satisfies L,
  editedTooLarge: { bg: "Коригираната зона е прекалено голяма или отдалечена. Намалете границата и опитайте отново.", en: "The edited area is too large or too far away. Reduce the boundary and try again." } satisfies L,
  editedFailed: { bg: "Коригираната граница не може да бъде обработена. Върнете се назад и опитайте с по-проста форма.", en: "The edited boundary could not be processed. Go back and try a simpler shape." } satisfies L,
  aboutTitle: { bg: "За анализа", en: "About the analysis" } satisfies L,
  aboutBody: {
    bg: [
      "Данните идват от OpenStreetMap и може да са непълни.",
      "Резултатът е ориентировъчен и не замества кадастрално или геодезическо измерване.",
      "Идея: др. Станислав Дарачев. Реализация: ITT Digital Hub.",
    ],
    en: [
      "The data come from OpenStreetMap and may be incomplete.",
      "Results are indicative and do not replace a cadastral or geodetic survey.",
      "Concept: Dr Stanislav Darachev. Built by ITT Digital Hub.",
    ],
  } satisfies L<string[]>,
  close: { bg: "Затвори", en: "Close" } satisfies L,
  admin: { bg: "Администрация", en: "Admin" } satisfies L,
  welcomeTitle: { bg: "Анализатор на населени места", en: "Settlement Analyzer" } satisfies L,
  welcomeLead: {
    bg: "Ориентировъчна граница, площи, сгради и улици от отворени данни.",
    en: "Indicative boundary, areas, buildings and streets from open data.",
  } satisfies L,
  loading: { bg: "Зареждане...", en: "Loading..." } satisfies L,
  loadErrorTitle: { bg: "Достъпът временно не може да бъде зареден", en: "Access could not be loaded" } satisfies L,
  fullName: { bg: "Име и фамилия", en: "Full name" } satisfies L,
  email: { bg: "Имейл", en: "Email" } satisfies L,
  organisation: { bg: "Организация / фирма", en: "Organisation" } satisfies L,
  organisationType: { bg: "Тип организация", en: "Organisation type" } satisfies L,
  organisationTypePlaceholder: { bg: "Изберете тип организация", en: "Select organisation type" } satisfies L,
  marketingConsent: {
    bg: "Искам новини за инструменти и услуги на ITT Digital Hub.",
    en: "I would like updates about ITT Digital Hub tools and services.",
  } satisfies L,
  submit: { bg: "Продължи", en: "Continue" } satisfies L,
  submitting: { bg: "Записване...", en: "Saving..." } satisfies L,
  privacyNoticeBefore: { bg: "С изпращането приемате", en: "By submitting you accept the" } satisfies L,
  privacyPolicy: { bg: "политиката за поверителност", en: "privacy policy" } satisfies L,
  privacyPageTitle: { bg: "Политика за поверителност", en: "Privacy policy" } satisfies L,
  required: { bg: "*", en: "*" } satisfies L,
  registerError: { bg: "Регистрацията не беше записана. Моля, опитайте отново.", en: "Registration was not saved. Please try again." } satisfies L,
  registerNameError: { bg: "Моля, въведете име и фамилия.", en: "Please enter your full name." } satisfies L,
  registerEmailError: { bg: "Моля, въведете валиден имейл.", en: "Please enter a valid email address." } satisfies L,
  registerOrgError: { bg: "Моля, въведете организация или фирма.", en: "Please enter an organisation." } satisfies L,
  registerTypeError: { bg: "Моля, изберете тип организация.", en: "Please select an organisation type." } satisfies L,
  registerDuplicate: {
    bg: "С този имейл вече има регистрация. Отворете инструмента от устройството, на което сте се регистрирали.",
    en: "This email is already registered. Open the tool from the device you registered on.",
  } satisfies L,
  invalidRequest: { bg: "Невалидна заявка.", en: "Invalid request." } satisfies L,
  ownerPreview: { bg: "Тестов режим — данните няма да бъдат записани.", en: "Test mode — data will not be saved." } satisfies L,
  testUser: { bg: "Тестов потребител", en: "Test user" } satisfies L,
  commandBar: { bg: "Управление на анализа", en: "Analysis controls" } satisfies L,
  mapRegion: { bg: "Интерактивна карта", en: "Interactive map" } satisfies L,
  layers: { bg: "Слоеве", en: "Layers" } satisfies L,
  layersAria: { bg: "Слоеве на картата", en: "Map layers" } satisfies L,
  analysisBoundary: { bg: "Граница на анализа", en: "Analysis boundary" } satisfies L,
  cadastreLayer: { bg: "Кадастър: урбанизирани имоти (извадка)", en: "Cadastre: urbanised parcels (sample)" } satisfies L,
  buildings: { bg: "Сгради", en: "Buildings" } satisfies L,
  pois: { bg: "Обществени обекти", en: "Public sites" } satisfies L,
  clearSearch: { bg: "Изчисти търсенето", en: "Clear search" } satisfies L,
  searching: { bg: "Търсене на населено място...", en: "Searching for a settlement..." } satisfies L,
  noResults: { bg: "Няма намерени населени места.", en: "No settlements found." } satisfies L,
  foundSettlements: { bg: "Намерени населени места", en: "Matching settlements" } satisfies L,
  bulgaria: { bg: "България", en: "Bulgaria" } satisfies L,
  municipality: { bg: "Община", en: "Municipality" } satisfies L,
  region: { bg: "Област", en: "Region" } satisfies L,
  results: { bg: "Резултати от анализа", en: "Analysis results" } satisfies L,
  profileLabel: { bg: "Профил", en: "Profile" } satisfies L,
  confidenceLabel: { bg: "Надеждност", en: "Confidence" } satisfies L,
  boundaryMethod: { bg: "Метод за границата", en: "Boundary method" } satisfies L,
  distribution: { bg: "Разпределение на територията", en: "Land-cover distribution" } satisfies L,
  category: { bg: "Категория", en: "Category" } satisfies L,
  areaM2: { bg: "Площ (м²)", en: "Area (m²)" } satisfies L,
  areaHa: { bg: "Площ (ха)", en: "Area (ha)" } satisfies L,
  total: { bg: "ОБЩО", en: "TOTAL" } satisfies L,
  kpis: { bg: "Ключови показатели", en: "Key indicators" } satisfies L,
  analysedArea: { bg: "Анализирана площ", en: "Analysed area" } satisfies L,
  roadNetwork: { bg: "Улична мрежа", en: "Street network" } satisfies L,
  buildingFootprint: { bg: "Площ на сградите", en: "Building footprint" } satisfies L,
  builtUp: { bg: "Застрояване", en: "Built-up" } satisfies L,
  averageBuilding: { bg: "Средна площ на сграда", en: "Average building area" } satisfies L,
  likelyResidential: { bg: "вероятно жилищни", en: "likely residential" } satisfies L,
  unknownBuildings: { bg: "неопределени сгради", en: "unclassified buildings" } satisfies L,
  details: { bg: "Допълнителни показатели", en: "Further indicators" } satisfies L,
  km2: { bg: "км²", en: "km²" } satisfies L,
  kmPerKm2: { bg: "км/км²", en: "km/km²" } satisfies L,
  perHa: { bg: "/ ха", en: "/ ha" } satisfies L,
  continue: { bg: "Продължи", en: "Continue" } satisfies L,
  closeMessage: { bg: "Затвори съобщението", en: "Dismiss message" } satisfies L,
  trackingOffline: { bg: "Анализаторът работи, но статистиката временно не се записва.", en: "The tool works, but statistics are not being recorded." } satisfies L,
  analysisUntracked: { bg: "Анализът е готов, но статистиката временно не беше записана.", en: "The analysis is ready, but statistics were not recorded." } satisfies L,
  bootstrapLoadError: { bg: "Достъпът временно не може да бъде зареден.", en: "Access could not be loaded." } satisfies L,
  confidenceHigh: { bg: "Висока", en: "High" } satisfies L,
  confidenceMedium: { bg: "Средна", en: "Medium" } satisfies L,
  confidenceLow: { bg: "Ниска", en: "Low" } satisfies L,
  ha: { bg: "ха", en: "ha" } satisfies L,
  km: { bg: "км", en: "km" } satisfies L,
  m2: { bg: "м²", en: "m²" } satisfies L,
  poiLabels: {
    bg: {
      school: "Училище",
      kindergarten: "Детска градина",
      townhall: "Кметство",
      clinic: "Медицински обект",
      doctors: "Лекарски кабинет",
      hospital: "Болница",
      pharmacy: "Аптека",
      place_of_worship: "Храм",
      community_centre: "Читалище / обществен център",
      library: "Библиотека",
      sports_centre: "Спортен обект",
      parking: "Обществен паркинг",
      grave_yard: "Гробище",
      sport: "Спортен обект",
      other: "Обществен обект",
    },
    en: {
      school: "School",
      kindergarten: "Kindergarten",
      townhall: "Town hall",
      clinic: "Clinic",
      doctors: "Doctor",
      hospital: "Hospital",
      pharmacy: "Pharmacy",
      place_of_worship: "Place of worship",
      community_centre: "Community centre",
      library: "Library",
      sports_centre: "Sports centre",
      parking: "Public parking",
      grave_yard: "Cemetery",
      sport: "Sports site",
      other: "Public site",
    },
  } satisfies L<Record<string, string>>,
  editBoundary: { bg: "Редактирай границата", en: "Edit boundary" } satisfies L,
  recalculate: { bg: "Преизчисли", en: "Recalculate" } satisfies L,
  cancel: { bg: "Отказ", en: "Cancel" } satisfies L,
  downloadCsv: { bg: "Изтегли CSV", en: "Download CSV" } satisfies L,
  downloadGeoJson: { bg: "Изтегли GeoJSON", en: "Download GeoJSON" } satisfies L,
  categories: {
    bg: {
      residential: "Жилищни площи",
      industrial: "Индустриални / търговски площи",
      roads: "Улици / транспорт",
      green: "Зелени площи",
      water: "Водни площи",
      agricultural: "Земеделски площи",
      other: "Други",
    },
    en: {
      residential: "Residential areas",
      industrial: "Industrial / commercial areas",
      roads: "Streets / transport",
      green: "Green areas",
      water: "Water",
      agricultural: "Agricultural land",
      other: "Other",
    },
  } satisfies L<Record<string, string>>,
  layerCategories: {
    bg: {
      residential: "Жилищни",
      industrial: "Индустрия",
      roads: "Улици",
      green: "Зелени",
      water: "Води",
      agricultural: "Земеделие",
      other: "Други",
    },
    en: {
      residential: "Residential",
      industrial: "Industry",
      roads: "Streets",
      green: "Green",
      water: "Water",
      agricultural: "Farmland",
      other: "Other",
    },
  } satisfies L<Record<string, string>>,
  profiles: {
    bg: {
      agriculturalDominant: "Преобладаващо земеделска структура",
      mixedResidentialIndustrial: "Смесена жилищно-индустриална структура",
      veryLowBuiltUp: "Много ниска плътност на застрояване",
      lowBuiltUp: "Ниска плътност на застрояване",
      mediumBuiltUp: "Средна плътност на застрояване",
      highBuiltUp: "Висока плътност на застрояване",
    },
    en: {
      agriculturalDominant: "Predominantly agricultural structure",
      mixedResidentialIndustrial: "Mixed residential–industrial structure",
      veryLowBuiltUp: "Very low built-up density",
      lowBuiltUp: "Low built-up density",
      mediumBuiltUp: "Medium built-up density",
      highBuiltUp: "High built-up density",
    },
  } satisfies L<Record<SettlementProfileCode, string>>,
  boundaryReasons: {
    bg: {
      manual: "Ръчно коригирана граница",
      openGeometry: "Подходяща отворена геометрия на населеното място",
      residentialLanduse: "Картографирана жилищна зона с контролиран периферен буфер",
      buildingCluster: "Свързана застроена зона по намерените сгради",
      centerBuffer: "Резервна компактна зона поради недостатъчни или прекалено разредени данни за сгради",
    },
    en: {
      manual: "Manually adjusted boundary",
      openGeometry: "Suitable open geometry of the settlement",
      residentialLanduse: "Mapped residential area with a controlled outer buffer",
      buildingCluster: "Connected built-up area from mapped buildings",
      centerBuffer: "Compact fallback zone because building data are insufficient or too sparse",
    },
  } satisfies L<Record<BoundaryReasonCode, string>>,
  analysisWarnings: {
    bg: {
      noBuildings: "В зоната не са намерени картографирани сгради.",
      noRoads: "В зоната не е намерена картографирана улична мрежа.",
      incompleteData: "Отворените данни за това населено място са непълни; резултатите са силно ориентировъчни.",
      dataExtentReached: "Застройката опира края на свалените данни. Градът може да е по-голям от показаната граница.",
    },
    en: {
      noBuildings: "No mapped buildings were found in the area.",
      noRoads: "No mapped street network was found in the area.",
      incompleteData: "Open data for this settlement are incomplete; results are highly indicative.",
      dataExtentReached: "Built-up area reaches the edge of the downloaded data. The city may be larger than this boundary.",
    },
  } satisfies L<Record<AnalysisWarningCode, string>>,
  confidenceReasons: {
    bg: {
      classifiedBuildings: "Класифицирани сгради: {value}%",
      explicitLanduse: "Територия с изрично предназначение: {value}%",
      otherAreas: "Други / некласифицирани площи: {value}%",
      unknownBuildings: "Неопределени сгради: {value}%",
    },
    en: {
      classifiedBuildings: "Classified buildings: {value}%",
      explicitLanduse: "Area with explicit land use: {value}%",
      otherAreas: "Other / unclassified areas: {value}%",
      unknownBuildings: "Unclassified buildings: {value}%",
    },
  } satisfies L<Record<ConfidenceReasonCode, string>>,
  confidenceLevels: {
    bg: { high: "Висока", medium: "Средна", low: "Ниска" },
    en: { high: "High", medium: "Medium", low: "Low" },
  } satisfies L<Record<ConfidenceLevel, string>>,
  stages: {
    bg: {
      idle: "",
      boundary: "Определяне на границата...",
      buildings: "Зареждане на сградите...",
      roads: "Зареждане на уличната мрежа...",
      landuse: "Анализ на предназначението на територията...",
      geometry: "Обработка на площите...",
      metrics: "Изчисляване на показателите...",
      map: "Подготовка на картата...",
      complete: "Анализът е завършен.",
    },
    en: {
      idle: "",
      boundary: "Determining the boundary...",
      buildings: "Loading buildings...",
      roads: "Loading the street network...",
      landuse: "Analysing land use...",
      geometry: "Processing areas...",
      metrics: "Calculating indicators...",
      map: "Preparing the map...",
      complete: "Analysis complete.",
    },
  } satisfies L<Record<string, string>>,
  privacy: {
    bg: {
      documentTitle: "Политика за поверителност · Анализатор на населени места",
      heading: "Политика за поверителност",
      collectTitle: "Какви данни събираме",
      collectBody: "При достъп събираме име и фамилия, имейл, организация и тип организация. Маркетинговото съгласие е по желание. След анализ можем да запишем името на населеното място и обобщени показатели от резултата.",
      whyTitle: "Защо ги използваме",
      whyBody: "Използваме данните, за да предоставим инструмента, да запазим достъпа ви между посещения и да подобряваме продукта.",
      usageTitle: "Използване на инструмента",
      usageBody: "Записваме посещения, регистрация, извършени анализи и използване на функции като редакция на граница или изтегляне на файлове, когато връзката със сървъра е налична.",
      marketingTitle: "Маркетингово съгласие",
      marketingBody: "Маркетинговото съгласие е отделно и не е условие за достъп. Можете да го оттеглите по имейл.",
      storageTitle: "Съхранение в браузъра",
      storageBody: "След регистрация запазваме сесийни бисквитки, за да поддържаме достъпа. Търсенето може да се кешира в localStorage. Геоданните за текущата сесия могат да се пазят в sessionStorage. Свалените пакети за анализ се пазят в IndexedDB на този браузър. Ако базата данни е временно недостъпна, браузърът може да запомни, че регистрацията е завършена.",
      thirdTitle: "Външни услуги",
      thirdBody: "Картата използва плочки на OpenStreetMap. Търсенето и геоданните минават през Nominatim и Overpass. Сайтът използва Vercel Analytics за обобщена статистика на посещенията.",
      retentionTitle: "Срок за съхранение",
      rightsTitle: "Вашите права",
      rightsBody: "Можете да поискате достъп, корекция, ограничаване или изтриване, както и да оттеглите маркетинговото съгласие. Посочете имейла, използван при регистрацията.",
      contactTitle: "Контакт",
      contactBefore: "Изпратете заявка до ",
    },
    en: {
      documentTitle: "Privacy policy · Settlement Analyzer",
      heading: "Privacy policy",
      collectTitle: "What we collect",
      collectBody: "On access we collect full name, email, organisation and organisation type. Marketing consent is optional. After an analysis we may record the settlement name and summary metrics from the result.",
      whyTitle: "Why we use them",
      whyBody: "We use the data to provide the tool, keep your access between visits, and improve the product.",
      usageTitle: "How the tool is used",
      usageBody: "We record visits, registration, completed analyses and use of features such as boundary editing or file download when the server connection is available.",
      marketingTitle: "Marketing consent",
      marketingBody: "Marketing consent is separate and is not a condition of access. You can withdraw it by email.",
      storageTitle: "Storage in the browser",
      storageBody: "After registration we keep session cookies so you remain signed in. Search results may be cached in localStorage. Geodata for the current session may be kept in sessionStorage. Downloaded analysis packs are stored in IndexedDB on this browser. If the database is temporarily unavailable, the browser may remember that registration was completed.",
      thirdTitle: "Third-party services",
      thirdBody: "The map uses OpenStreetMap tiles. Search and geodata go through Nominatim and Overpass. The site uses Vercel Analytics for aggregated page-view statistics.",
      retentionTitle: "Retention",
      rightsTitle: "Your rights",
      rightsBody: "You can request access, correction, restriction or deletion, and you can withdraw marketing consent. Quote the email used at registration.",
      contactTitle: "Contact",
      contactBefore: "Send a request to ",
    },
  } satisfies L<Record<string, string>>,
};

export function sa(locale: Locale) {
  return Object.fromEntries(
    Object.entries(settlementAnalyzer).map(([key, value]) => [key, value[locale]]),
  ) as { [K in keyof typeof settlementAnalyzer]: (typeof settlementAnalyzer)[K][Locale] };
}
