/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=platform/gateway/wrangler.jsonc --include-runtime=false platform/gateway/worker-configuration.d.ts` (hash: 3ff88dca4e702b7a850f35d159a1ff90)
interface __BaseEnv_Env {
	GATEWAY_ENV: "production";
	AGENT_HUB_ORIGIN: "https://agent.ittdigitalhub.org";
	ALLOWED_ORIGINS: "https://ittdigitalhub.org,http://localhost:3000";
	UPSTREAM_TIMEOUT_MS: "45000";
	AGENT_HUB_SHARED_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GATEWAY_ENV" | "AGENT_HUB_ORIGIN" | "ALLOWED_ORIGINS" | "UPSTREAM_TIMEOUT_MS" | "AGENT_HUB_SHARED_SECRET">> {}
}
